POST https://myfly-fishing-api.herokuapp.com
content-type: application/json

{
    "id": "1",
    "bait": ["Hares Ear", "Ant"],
    "location": "Other location",
    "img": "https://img.search.brave.com/liCzQTkCW0p20C40rRcsGZCnLXm1E4cH3eZCE9nW5to/rs:fit:864:570:1/g:ce/aHR0cHM6Ly93d3cu/bWFyaW9ub25saW5l/LmNvbS9tZWRpYS8y/MDE1LzAzL1JhaW5i/b3ctVHJvdXQuanBn",
    "date": "4/1/22",
    "fish": [{"species":"rainbow", "length":"14"}]
}

###
GET https://myfly-fishing-api.herokuapp.com/

###
GET https://myfly-fishing-api.herokuapp.com/:ID

###
DELETE https://myfly-fishing-api.herokuapp.com/:ID

###
PUT https://myfly-fishing-api.herokuapp.com/:ID
content-type: application/json

{
    "id": "1",
    "bait": ["Hares Ear", "Ant"],
    "location": "test location",
    "img": "https://img.search.brave.com/liCzQTkCW0p20C40rRcsGZCnLXm1E4cH3eZCE9nW5to/rs:fit:864:570:1/g:ce/aHR0cHM6Ly93d3cu/bWFyaW9ub25saW5l/LmNvbS9tZWRpYS8y/MDE1LzAzL1JhaW5i/b3ctVHJvdXQuanBn",
    "date": "4/1/22",
    "fish": [{"species":"cutthrout", "length":"14"}]
}
